car_stat/car_stat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url('stat/', include('get_car_info.urls')),
]

car_stat/get_car_info/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('start/', views.StartView.as_view(), name='start'),

    path('list/<brand>/<model>/', views.InfoView.as_view(), name='info'),

    path('ajax/load-models/', views.load_models, name='ajax_load_models'),
]

car_stat/get_car_info/models.py
from django.db import models
from django.db.models import Avg

import datetime
import calendar


def create_month_statistics_list(vehicles, mindate, whole_avg_price):
    price_list = []
    month_list = []
    quantity_list = []
    now = datetime.datetime.now()
    start = 12 * int(mindate.year) + int(mindate.month) - 1
    finish = 12 * int(now.year) + int(now.month)
    for step in range(start, finish):
        year, month = divmod(step, 12)
        vv = vehicles.filter(date_create__year=year, date_create__month=month + 1)
        try:
            avg_price = format(round(vv.aggregate(Avg('price')).get('price__avg'), -2), '.2f')
        except:
            avg_price = format(round(whole_avg_price, -2), '.2f')
        price_list.append(avg_price)
        total = vv.count()
        quantity_list.append(total)
        cur = str(calendar.month_name[month + 1]) + ', ' + str(year)
        month_list.append(cur)

    return price_list, month_list, quantity_list


class NewManager(models.Manager):
    def get_earliest_date(self, brand, model):
        return self.filter(brand=brand).filter(model=model).earliest('date_create').date_create

    def filter_car_with_gen(self, brand, model, year_manufacture):
        vehicles_no_gen = Vehicle.objects.filter(brand__name=brand, model__name=model,
                                                 year_manufacture=year_manufacture)
        gen = vehicles_no_gen.values_list('generation__name', flat=True).distinct()
        vehicles_with_gen = Vehicle.objects.filter(brand=brand, model=model, generation__name=gen.first())
        #vehicles_with_gen = Vehicle.objects.filter(brand=brand, model=model, generation__name__in=gen)   # all generations
        return vehicles_with_gen, gen


class VehicleBrand(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name',]

class VehicleModel(models.Model):
    name = models.CharField(max_length=128, unique=True)
    brand = models.ForeignKey(VehicleBrand, on_delete=models.PROTECT, blank=True, null=True)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name

class VehicleGeneration(models.Model):
    name = models.CharField(max_length=128, unique=True)
    brand = models.ForeignKey(VehicleBrand, on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return self.name

class VehicleCondition(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class VehicleBodyType(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class VehicleEngineType(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class VehicleTransmission(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class VehicleDrive(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class VehicleWheel(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class VehicleColor(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class VehicleEquipment(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class VehicleSellerType(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class Region(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=128, unique=True)
    region = models.ForeignKey(Region, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

class Vehicle(models.Model):
    link = models.CharField(max_length=256, unique=True, blank=False, null=False)
    date_create = models.DateTimeField(auto_now_add=True)
    date_finished = models.DateTimeField(blank=True, null=True)
    price = models.IntegerField(blank=False)
    brand = models.ForeignKey(VehicleBrand, on_delete=models.PROTECT)
    model = models.ForeignKey(VehicleModel, on_delete=models.PROTECT)
    generation = models.ForeignKey(VehicleGeneration, on_delete=models.PROTECT)
    modification = models.CharField(max_length=128, blank=True)
    year_manufacture = models.IntegerField(blank=False)
    mileage = models.IntegerField(blank=False)
    condition = models.ForeignKey(VehicleCondition, on_delete=models.PROTECT)
    quantity_owner = models.CharField(max_length=2, blank=False)
    body_type = models.ForeignKey(VehicleBodyType, on_delete=models.PROTECT)
    quantity_doors = models.IntegerField()
    engine_type = models.ForeignKey(VehicleEngineType, on_delete=models.PROTECT)
    transmission = models.ForeignKey(VehicleTransmission, on_delete=models.PROTECT)
    drive = models.ForeignKey(VehicleDrive, on_delete=models.PROTECT)
    wheel = models.ForeignKey(VehicleWheel, on_delete=models.PROTECT)
    color = models.ForeignKey(VehicleColor, on_delete=models.PROTECT)
    equipment = models.ForeignKey(VehicleEquipment, on_delete=models.PROTECT, blank=True, null=True)
    address = models.CharField(max_length=128)
    region = models.ForeignKey(Region, on_delete=models.PROTECT, blank=True, null=True)
    city = models.ForeignKey(City, on_delete=models.PROTECT, blank=True, null=True)
    seller_type = models.ForeignKey(VehicleSellerType, on_delete=models.PROTECT)

    objects = NewManager()

    def __str__(self):
        return self.link

car_stat/get_car_info/forms.py
from django import forms
from django.db.models import Min

from .models import *

import datetime


class StartForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = ['brand', 'model', 'year_manufacture', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['model'].queryset = VehicleModel.objects.none()

        if 'brand' in self.data:
            try:
                brand_id = int(self.data.get('brand'))
                self.fields['model'].queryset = VehicleModel.objects.filter(brand=brand_id).order_by('name')
            except (ValueError, TypeError):
                pass

    def clean(self):
        super().clean()
        brand = self.cleaned_data["brand"]
        model = self.cleaned_data["model"]
        year = self.cleaned_data["year_manufacture"]
        vehicles = Vehicle.objects.filter(brand=brand).filter(model=model)

        min_year = vehicles.aggregate(Min('year_manufacture')).get('year_manufacture__min')

        max_year = int(datetime.datetime.now().year)
        if year < min_year:
            raise forms.ValidationError('Chosen year is too low, min year is {}'.format(min_year))
        if year > max_year:
            raise forms.ValidationError('Chosen year is too big, max year is {}'.format(max_year))

        if vehicles.filter(year_manufacture=year).count() == 0:
            raise forms.ValidationError('No cars for this filter')

car_stat/get_car_info/views.py
from django.views.generic.edit import FormView
from django.views.generic import ListView, TemplateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404


from .forms import StartForm
from .models import *


class StartView(FormView):
    form_class = StartForm
    template_name = 'get_car_info/start.html'
    success_url = reverse_lazy('start')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            brand = form.cleaned_data.get('brand')
            model = form.cleaned_data.get('model')
            year_manufacture = form.cleaned_data.get('year_manufacture')
            self.request.session['year'] = year_manufacture

            return redirect(reverse_lazy('info', kwargs={'brand':brand,'model':model,}))
        return render(request, self.template_name, {'form': form})

class InfoView(TemplateView):
    template_name = 'get_car_info/brandmodel.html'

    def get_context_data(self, *args, **kwargs):
        context = super(InfoView, self).get_context_data(*args, **kwargs)
        self.brand = get_object_or_404(VehicleBrand, name=self.kwargs['brand'])
        self.model = get_object_or_404(VehicleModel, name=self.kwargs['model'])
        year_manufacture = self.request.session['year']

        vehicles, gen = Vehicle.objects.filter_car_with_gen(brand=self.brand,
                                                            model=self.model,
                                                            year_manufacture=year_manufacture)
        if len(gen) > 1:
            context['gen_list'] = gen
        average_data = vehicles.aggregate(Avg('price'), Avg('mileage'))
        mindate = Vehicle.objects.get_earliest_date(self.brand, self.model)

        context['personal_seller'] = round(
            vehicles.filter(seller_type__name='Частное лицо').count() / vehicles.count(), 2
        ) * 100

        context['price_list'], context['month_list'], context['quantity_list'] = \
            create_month_statistics_list(vehicles, mindate, average_data.get('price__avg'))
        context['avg_price'] = format(round(average_data.get('price__avg'), -2), '.2f')
        context['year_manufacture'] = year_manufacture
        context['generation'] = gen.first()
        context['avg_quantity'] = round(
            sum(context['quantity_list']) / len(context['quantity_list'])
        )
        context['avg_mileage'] = format(round(average_data.get('mileage__avg'), -2), '.2f')

        return context

def load_models(request):
    brand_id = request.GET.get('brand_id')
    models = VehicleModel.objects.filter(brand_id=brand_id).all()
    return render(request, 'get_car_info/model_dropdown_list_options.html', {'models': models})

car_stat/get_car_info/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">

    <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" rel="stylesheet">
    <script crossorigin="anonymous"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>


    <style>
        .border-left-primary {
          border-left: 0.25rem solid #4e73df !important;
        }
        .border-left-warning {
          border-left: 0.25rem solid #f6c23e !important;
        }
        .border-left-success {
          border-left: 0.25rem solid #1cc88a !important;
        }
        .border-left-info {
          border-left: 0.25rem solid #36b9cc !important;
        }


    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-center">
    <a class="navbar-brand" href="#">Site</a>
    <button aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"
            data-target="#navbarNavAltMarkup" data-toggle="collapse" type="button">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-link" href=#>Home</a>
            <a class="nav-link" href="{% url 'start' %}">Start</a>


        </div>
    </div>
</nav>

{% if messages %}
{% for message in messages %}
<div class="alert alert-success">{{ message }}</div>
{% endfor %}
{% endif %}

{% block content %}

{% endblock %}

<script crossorigin="anonymous"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_brand").change(function () {
        const url = $("#startForm").attr("data-models-url");
        const brandId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'brand_id': brandId
            },
            success: function (data) {
                $("#id_model").html(data);
            }
        });
    });




</script>


<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

</body>
</html>